#!/bin/bash
MXE_PATH=/mnt/mxe-build-x64/mxe
export PATH=$MXE_PATH/usr/bin:$PATH

NB_CORES=`nproc`

cd ..

MXE_INCLUDE_PATH=$MXE_PATH/usr/x86_64-w64-mingw32.static/include
MXE_LIB_PATH=$MXE_PATH/usr/x86_64-w64-mingw32.static/lib

x86_64-w64-mingw32.static-qmake-qt5 \
	BOOST_LIB_SUFFIX=-mt \
	BOOST_THREAD_LIB_SUFFIX=_win32-mt \
	BOOST_INCLUDE_PATH=$MXE_INCLUDE_PATH/boost \
	BOOST_LIB_PATH=$MXE_LIB_PATH \
	OPENSSL_INCLUDE_PATH=$MXE_INCLUDE_PATH/openssl \
	OPENSSL_LIB_PATH=$MXE_LIB_PATH \
	BDB_INCLUDE_PATH=$MXE_INCLUDE_PATH \
	BDB_LIB_PATH=$MXE_LIB_PATH \
	MINIUPNPC_INCLUDE_PATH=$MXE_INCLUDE_PATH \
	MINIUPNPC_LIB_PATH=$MXE_LIB_PATH \
	QMAKE_TARGET.arch=x86_64 \
	QMAKE_LRELEASE=$MXE_PATH/usr/x86_64-w64-mingw32.static/qt5/bin/lrelease Ignition.pro

make -j$NB_CORES -f Makefile.Release
